export const categories = ['Food', 'Transport', 'Shopping', 'Household', 'Bills', 'EMI', 'Family', 'Health', 'Travel', 'Other'] as const;
export const paymentMethods = ['Cash', 'Debit Card', 'Credit Card', 'Bank'] as const;
export const currencies = ['NPR', 'INR', 'USD'] as const;
export type Currency = typeof currencies[number];
export type Category = typeof categories[number];
export const subcategories: Record<Category, readonly string[]> = {
 Food:['Meals','Tea & coffee','Dining out'], Transport:['Fuel','Taxi','Public transport','Vehicle servicing'], Shopping:['Clothes','Electronics','Personal care'], Household:['Groceries','Vegetables & fruits','Milk & dairy','Cooking gas','Cleaning supplies','Domestic help','Other household'], Bills:['Rent','Electricity','Water','Internet','Mobile recharge','Subscriptions','Insurance'], EMI:['Vehicle loan','Home loan','Personal loan','Other loan'], Family:['Education','Childcare','Family support','Gifts'], Health:['Medicines','Doctor','Tests'], Travel:['Hotel','Tickets','Activities'], Other:['Other']
};
export type Expense = { id: string; amountMinor: number; currency: Currency; category: Category; paymentMethod: typeof paymentMethods[number] | 'Card'; note: string; date: string; createdAt: string; updatedAt: string; userId: string | null; subcategory?: string; kind?: 'expense' | 'transfer'; cardId?: string; principalMinor?: number; interestMinor?: number; scheduleId?: string; scheduledFor?: string };
export type CardAccount = { id:string;name:string;currency:Currency;openingBalanceMinor:number;dueDay:number; };
export type Recurring = { id:string;name:string;amountMinor:number;currency:Currency;category:Category;subcategory:string;paymentMethod:typeof paymentMethods[number];nextDue:string;dueDay:number;remaining:number|null;interestMinor:number;cardId?:string };
export type Ledger = { version:2;expenses:Expense[];cards:CardAccount[];recurring:Recurring[] };
export function localDate(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
export function validDate(value:unknown): value is string { if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(value+'T12:00:00');return !Number.isNaN(date.getTime())&&localDate(date)===value; }
export function parseAmount(value: string) { if (!/^\d+(\.\d{1,2})?$/.test(value)) throw new Error('Enter a positive amount with up to two decimals.'); const amount = Math.round(Number(value)*100); if (!Number.isSafeInteger(amount) || amount <= 0 || amount > 99999999999) throw new Error('Amount must be between 0.01 and 999,999,999.99.'); return amount; }
export function money(amountMinor: number, currency: Currency = 'NPR') { return new Intl.NumberFormat('en-NP', {style:'currency',currency, currencyDisplay:'code',minimumFractionDigits:2,maximumFractionDigits:2}).format(amountMinor/100); }
const minor=(x:unknown)=>typeof x==='number'&&Number.isSafeInteger(x)&&x>=0&&x<=99999999999;
export function isExpense(x: unknown): x is Expense { if(!x || typeof x !== 'object') return false; const e=x as Expense; return typeof e.id==='string' && minor(e.amountMinor) && e.amountMinor>0 && currencies.includes(e.currency) && categories.includes(e.category) && ([...paymentMethods,'Card'] as readonly string[]).includes(e.paymentMethod) && typeof e.note==='string' && validDate(e.date) && typeof e.createdAt==='string' && typeof e.updatedAt==='string' && (e.userId===null || typeof e.userId==='string') && (e.kind===undefined || ['expense','transfer'].includes(e.kind)) && (e.subcategory===undefined || typeof e.subcategory==='string') && (e.cardId===undefined||typeof e.cardId==='string') && (e.principalMinor===undefined||minor(e.principalMinor)) && (e.interestMinor===undefined||minor(e.interestMinor)) && (e.scheduleId===undefined||typeof e.scheduleId==='string') && (e.scheduledFor===undefined||validDate(e.scheduledFor)); }
export function isCard(x:unknown): x is CardAccount {if(!x||typeof x!=='object')return false;const c=x as CardAccount;return typeof c.id==='string'&&typeof c.name==='string'&&currencies.includes(c.currency)&&minor(c.openingBalanceMinor)&&Number.isInteger(c.dueDay)&&c.dueDay>=1&&c.dueDay<=31;}
export function isRecurring(x:unknown):x is Recurring {if(!x||typeof x!=='object')return false;const r=x as Recurring;return typeof r.id==='string'&&typeof r.name==='string'&&minor(r.amountMinor)&&r.amountMinor>0&&currencies.includes(r.currency)&&categories.includes(r.category)&&typeof r.subcategory==='string'&&paymentMethods.includes(r.paymentMethod)&&validDate(r.nextDue)&&Number.isInteger(r.dueDay)&&r.dueDay>=1&&r.dueDay<=31&&(r.remaining===null||Number.isInteger(r.remaining)&&r.remaining>0)&&minor(r.interestMinor)&&r.interestMinor<=r.amountMinor&&(r.cardId===undefined||typeof r.cardId==='string');}
export function isSpending(e:Expense){return e.kind!=='transfer';}
export function totals(expenses: Expense[], today: string, currency: Currency) { const selected=expenses.filter(e=>e.currency===currency&&isSpending(e)); return {today:selected.filter(e=>e.date===today).reduce((s,e)=>s+e.amountMinor,0),month:selected.filter(e=>e.date.slice(0,7)===today.slice(0,7)).reduce((s,e)=>s+e.amountMinor,0)}; }
export function nextMonthlyDate(current:string,dueDay:number){const d=new Date(current+'T12:00:00');const y=d.getFullYear(),m=d.getMonth()+1;const last=new Date(y,m+1,0).getDate();return localDate(new Date(y,m,Math.min(dueDay,last)));}
export function cardBalance(card:CardAccount,expenses:Expense[]){return expenses.filter(e=>e.cardId===card.id&&e.currency===card.currency).reduce((sum,e)=>sum+(e.kind==='transfer'?-e.amountMinor:e.paymentMethod==='Credit Card'?e.amountMinor:0),card.openingBalanceMinor);}
export function payRecurring(state:Ledger,id:string,today:string):Ledger { const r=state.recurring.find(x=>x.id===id);if(!r)throw new Error('This scheduled payment no longer exists.');if(r.nextDue>today)throw new Error('This payment is not due yet.');if(state.expenses.some(e=>e.scheduleId===id&&e.scheduledFor===r.nextDue))throw new Error('This instalment has already been paid.');const now=new Date().toISOString();const e:Expense={id:crypto.randomUUID(),amountMinor:r.amountMinor,currency:r.currency,category:r.category,subcategory:r.subcategory,paymentMethod:r.paymentMethod,note:r.name,date:today,createdAt:now,updatedAt:now,userId:null,kind:'expense',cardId:r.cardId,scheduleId:r.id,scheduledFor:r.nextDue,...(r.category==='EMI'?{interestMinor:r.interestMinor,principalMinor:r.amountMinor-r.interestMinor}:{})};return {...state,expenses:[...state.expenses,e],recurring:state.recurring.flatMap(x=>x.id!==id?[x]:x.remaining===1?[]:[{...x,nextDue:nextMonthlyDate(x.nextDue,x.dueDay),remaining:x.remaining===null?null:x.remaining-1}])};}
