'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Banknote, Check, ChevronRight, CreditCard, Download, HeartPulse, House, LayoutDashboard, Leaf, Plus, ReceiptText, ShoppingBag, TramFront, Trash2, Utensils, Wallet, X, Landmark, MoreHorizontal } from 'lucide-react';
import { categories, currencies, Currency, Expense, localDate, money, parseAmount, paymentMethods, totals } from '@/lib/expenses';
import { localExpenseRepository } from '@/lib/storage';
const categoryIcons={Food:Utensils,Transport:TramFront,Shopping:ShoppingBag,Home:House,Health:HeartPulse,Other:MoreHorizontal};
type InstallEvent = Event & {prompt():Promise<void>;userChoice:Promise<{outcome:string}>};
export default function Kharcha(){
 const [expenses,setExpenses]=useState<Expense[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[blocked,setBlocked]=useState(false),[tab,setTab]=useState('overview'),[currency,setCurrency]=useState<Currency>('NPR'),[today,setToday]=useState(localDate()),[install,setInstall]=useState<InstallEvent|null>(null),[notice,setNotice]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),amountInput=useRef<HTMLInputElement>(null);
 const [amount,setAmount]=useState(''),[category,setCategory]=useState<Expense['category']>('Food'),[method,setMethod]=useState<Expense['paymentMethod']>('Cash'),[note,setNote]=useState(''),[date,setDate]=useState(localDate());
 useEffect(()=>{try{setExpenses(localExpenseRepository.list());}catch(e){setError((e as Error).message);setBlocked(true);}setReady(true);const tick=()=>setToday(localDate());const timer=setInterval(tick,30000); const update=()=>{try{setExpenses(localExpenseRepository.list());}catch{setError('Could not refresh saved expenses.');setBlocked(true);}};window.addEventListener('storage',update); const handler=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent);};window.addEventListener('beforeinstallprompt',handler);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>setNotice('Offline mode is unavailable in this browser.'));return()=>{clearInterval(timer);window.removeEventListener('storage',update);window.removeEventListener('beforeinstallprompt',handler);};},[]);
 const sum=totals(expenses,today,currency),monthExpenses=expenses.filter(e=>e.currency===currency&&e.date.slice(0,7)===today.slice(0,7)),transactions=expenses.filter(e=>e.currency===currency).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 function open(){setAmount('');setNote('');setDate(localDate());setError('');dialog.current?.showModal();amountInput.current?.focus();}
 function persist(next:Expense[]){if(blocked){setError('Saved data is unreadable. Please recover it before adding expenses.');return false;}try{localExpenseRepository.save(next);setExpenses(next);setError('');return true;}catch{setError('Unable to save. Your device storage may be full or disabled.');return false;}}
 function save(e:React.FormEvent){e.preventDefault();try{const amountMinor=parseAmount(amount);if(!date||date>localDate())throw new Error('Choose today or a past date.');const now=new Date().toISOString();const fresh=localExpenseRepository.list();if(persist([...fresh,{id:crypto.randomUUID(),amountMinor,currency,category,paymentMethod:method,note:note.trim(),date,createdAt:now,updatedAt:now,userId:null}])){dialog.current?.close();setNotice('Expense saved. You’re all caught up.');}}catch(e){setError((e as Error).message);}}
 function remove(id:string){if(!confirm('Delete this expense?'))return;try{if(persist(localExpenseRepository.list().filter(e=>e.id!==id)))setNotice('Expense deleted.');}catch(e){setError((e as Error).message);}}
 function exportData(){const blob=new Blob([JSON.stringify({version:1,expenses},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`kharcha-backup-${today}.json`;a.click();URL.revokeObjectURL(url);}
 const monthLabel=new Date(today+'T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'});
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/" aria-label="Kharcha home"><span className="logo">k<span>•</span></span>kharcha<span className="brand-dot">.</span></a><p className="tagline">A little clarity. Every day.</p><div className="side-nav"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><LayoutDashboard size={20}/>Overview</button><button className={tab==='transactions'?'active':''} onClick={()=>setTab('transactions')}><ReceiptText size={20}/>Transactions</button></div><div className="side-bottom"><Leaf size={24}/><h3>Small habits.<br/>A clearer tomorrow.</h3><p>Know where your money goes,<br/>one expense at a time.</p><span><span className="status-dot"/> Stored on your device</span></div></aside>
 <main><header><div className="mobile-brand">kharcha<span>.</span></div><div className="breadcrumb">Your personal money space</div><div className="header-actions"><label className="currency"><Wallet size={16}/><select aria-label="Display and new expense currency" value={currency} onChange={e=>setCurrency(e.target.value as Currency)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><span className="avatar">SK</span></div></header>
 <div className="content"><section className="heading"><div><div className="eyebrow">EVERYDAY SPENDING, MADE SIMPLE</div><h1>{tab==='overview'?'Your money, at a glance.':'Every little expense.'}</h1><p>{tab==='overview'?'A clear view of what you spend. More room for what matters.':'Your spending story, one transaction at a time.'}</p></div><button className="primary desktop-add" disabled={!ready||blocked} onClick={open}><Plus size={18}/> Add expense</button></section>
 {error&&<div className="alert" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {!ready?<p role="status">Loading your expenses…</p>:<>{tab==='overview'&&<><section className="summary-grid"><div className="month-card"><div className="card-top"><span>This month</span><span className="round-icon"><Wallet size={19}/></span></div><div className="total">{money(sum.month,currency)}</div><div className="month-footer"><span>{monthLabel}</span><span>{monthExpenses.length} expenses <ArrowUpRight size={16}/></span></div><div className="decor-circle"/></div><div className="today-card"><div className="card-top"><span>Spent today</span><span className="light-round"><ArrowUpRight size={19}/></span></div><div className="total">{money(sum.today,currency)}</div><p>{new Date(today+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}<span className="tiny-dot"/>{transactions.filter(e=>e.date===today).length} expenses</p></div></section>
 <section className="category-section"><div className="section-title"><h2>Where it goes</h2><span>This month</span></div><div className="category-grid">{categories.map(c=>{const Icon=categoryIcons[c];const amount=monthExpenses.filter(e=>e.category===c).reduce((s,e)=>s+e.amountMinor,0);return <div className="category-card" key={c}><span className={`category-icon ${c.toLowerCase()}`}><Icon size={20}/></span><span className="category-name">{c}</span><strong>{money(amount,currency)}</strong><div className="track"><div style={{width:`${sum.month?amount/sum.month*100:0}%`}}/></div></div>;})}</div></section></>}
 <section className="transactions"><div className="section-title"><h2>{tab==='overview'?'Recent transactions':'All transactions'} <span className="count">{transactions.length}</span></h2>{tab==='overview'&&<button className="text-button" onClick={()=>setTab('transactions')}>View all <ChevronRight size={16}/></button>}</div>{transactions.length===0?<div className="empty"><span className="empty-icon"><ReceiptText size={30}/></span><h3>A fresh start for your spending.</h3><p>Add your first expense. We’ll take care of the bigger picture.</p><button className="outline" onClick={open} disabled={blocked}><Plus size={17}/> Add your first expense</button></div>:<div className="transaction-list">{(tab==='overview'?transactions.slice(0,5):transactions).map(e=>{const Icon=categoryIcons[e.category];return <div className="transaction" key={e.id}><span className={`category-icon ${e.category.toLowerCase()}`}><Icon size={20}/></span><div className="transaction-info"><strong>{e.note||e.category}</strong><span>{e.category} <span>·</span> {e.paymentMethod} <span>·</span> {e.date===today?'Today':new Date(e.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span></div><strong className="transaction-amount">−{money(e.amountMinor,e.currency)}</strong><button className="delete" aria-label={`Delete ${e.note||e.category} expense`} onClick={()=>remove(e.id)}><Trash2 size={16}/></button></div>;})}</div>}</section></>}
 <footer><span><span className="status-dot"/>Private by default. Saved on this device.</span><div><button onClick={exportData} disabled={!ready||blocked}><Download size={14}/> Export backup</button>{install?<button onClick={async()=>{await install.prompt();await install.userChoice;setInstall(null);}}>Install Kharcha <ArrowDownLeft size={14}/></button>:<button onClick={()=>setNotice('To install: on Android, use your browser menu → Install app. On iPhone, use Safari → Share → Add to Home Screen. HTTPS hosting is required.')}>Install help <ArrowUpRight size={14}/></button>}</div></footer>
 </div></main><nav className="mobile-nav" aria-label="Main navigation"><button className={tab==='overview'?'selected':''} onClick={()=>setTab('overview')}><LayoutDashboard size={21}/>Overview</button><button className="add-fab" aria-label="Add expense" onClick={open} disabled={!ready||blocked}><Plus size={25}/></button><button className={tab==='transactions'?'selected':''} onClick={()=>setTab('transactions')}><ReceiptText size={21}/>Activity</button></nav>
 <dialog ref={dialog} onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><form onSubmit={save}><div className="modal-header"><div><div className="eyebrow">THE LITTLE THINGS ADD UP</div><h2>Add an expense</h2></div><button type="button" className="close" aria-label="Close expense form" onClick={()=>dialog.current?.close()}><X/></button></div><label className="amount-label" htmlFor="amount">How much did you spend?</label><div className="amount-field"><span>{currency}</span><input ref={amountInput} id="amount" inputMode="decimal" placeholder="0.00" autoComplete="off" value={amount} onChange={e=>setAmount(e.target.value)} required/></div><fieldset><legend>Category</legend><div className="category-picker">{categories.map(c=>{const Icon=categoryIcons[c];return <button type="button" key={c} aria-pressed={category===c} className={category===c?'chosen':''} onClick={()=>setCategory(c)}><Icon size={20}/>{c}</button>;})}</div></fieldset><fieldset><legend>Paid with</legend><div className="payment-picker">{paymentMethods.map(m=>{const Icon=m==='Cash'?Banknote:m==='Card'?CreditCard:Landmark;return <button type="button" key={m} aria-pressed={method===m} className={method===m?'chosen':''} onClick={()=>setMethod(m)}><Icon size={18}/>{m}</button>;})}</div></fieldset><div className="form-row"><label>Note <span>(optional)</span><input maxLength={120} placeholder="What was it for?" value={note} onChange={e=>setNote(e.target.value)}/></label><label>Date<input type="date" max={today} value={date} onChange={e=>setDate(e.target.value)} required/></label></div>{error&&<p className="alert" role="alert">{error}</p>}<button className="primary save" type="submit"><Check size={18}/> Save expense</button><p className="form-footnote">Just for you. Saved locally in your browser.</p></form></dialog></div>;
}
